### ISSUE TITLE
Add detailed Python env info to kernels

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter-powertoys#36]
Would be nice if we can see all the packages installed for environments (both the ones in the "Kernel Specifications" and in the "Active Jupyter Sessions"). Also, the dropdown for an Active Jupyter Sessions doesn't do anything (orange circle), and that's where I'd expect this information to be at:
![image](https://user-images.githubusercontent.com/10833267/171939024-dcd6cd7d-2777-4f2f-8904-9e310bb28d5c.png)

As a reference, kind of like how Don's Python Environment Manager lists "Info" and "Packages" for each env:
![image](https://user-images.githubusercontent.com/10833267/171938826-abff1851-0d08-4bac-b8ae-4f8baf145300.png)

**Comment by cipri-tom** [comment]
For the kernels, it would be nice to see this, yes.

But for the Active sessions, I think what is really important is to show which notebook is using that session. It is not of much use to see two entries in there if I can't know which one is which:

![Screenshot 2023-06-30 at 16 43 30](https://github.com/microsoft/vscode-jupyter-powertoys/assets/2991890/68aad4a7-62e7-43be-add0-bc2f4be6783d)


 In Jupyter, the running notebooks are shown with their name, rather than kernel's name (this is mentioned to the right, but now is the first time I notice it):
![Screenshot 2023-06-30 at 16 49 22](https://github.com/microsoft/vscode-jupyter-powertoys/assets/2991890/a6df457b-0ede-4c76-9707-0507ac5c5a83)

**Comment by DonJayamanne** [comment]
Closing this issue as not planned for now,
@minsa110 If you think this is still required, please feel free to re-open this, I'm assuming we're no longer planning on working on this feature.
If i'm wrong, please do feel free to re-open or create thie again.
